baseURL = "https://maxbanister.com/"
languageCode = "en-us"
title = "Max Banister's Notes"
theme = "default"

[params]
    subtitle = "The boys have been retowned."

enableGitInfo = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "pubdate"]
  date = ["pubdate", "date", "lastmod", "modified"]
