baseURL = "https://maxbanister.com/"
languageCode = "en-us"
title = "Max Banister's Notes"
theme = "default"
enableGitInfo = true

[params]
    subtitle = "The boys are retowned."

[frontmatter]
    lastmod = ["lastmod", ":git", ":fileModTime"]
    date = ["date", ":fileModTime", "lastmod"]

[mediaTypes]
    [mediaTypes."application/activity+json"]
        suffixes = ["json"]

[outputFormats]
    [outputFormats.activity_outbox]
        mediaType = "application/activity+json"
        isPlainText = true
        notAlternative = true
        baseName = "outbox"
        path = "ap"

[outputs]
    home = ["html", "rss", "activity_outbox"]
