baseURL = "https://maxbanister.com/"
languageCode = "en-us"
title = "Max Banister's Notes"
theme = "default"
enableGitInfo = true

[params]
    subtitle = "The boys have been retowned."


[frontmatter]
    lastmod = ["lastmod", ":git", "modified", "pubdate"]
    date = ["pubdate", "date", "lastmod", "modified"]
