[build]
	publish = "/public"
	edge-functions = "/netlify/edge-functions"

[build.environment]
	GO_VERSION = "1.23"

[functions]
	directory = "netlify/functions"
	included_files = ["./firebase-svc.json"]

[[edge_functions]]
	path = "/ap/inboxasdfasdf"
	function = "inbox"

[[edge_functions]]
	path = "/posts/*"
	function = "post2activity"

[[redirects]]
	from="/ap/outbox"
	to="/ap/outbox.json"
	status = 200

[[redirects]]
	from="/ap/*"
	to="/.netlify/functions/:splat"
	status = 200

[[headers]]
	for = "/ap/user/blog"
	[headers.values]
		Content-Type = "application/activity+json"

[[headers]]
	for = "/.well-known/webfinger"
	[headers.values]
		Content-Type = "application/activity+json"

[[headers]]
	for = "/posts/*"
	[headers.values]
		Content-Type = "text/html; charset=utf-8"