[build]
	publish = "/public"
	edge-functions = "/netlify/edge-functions"

[build.environment]
	GO_VERSION="1.23"

[functions]
  directory = "/netlify/functions"

[[redirects]]
	from="/ap/*"
	to="/.netlify/functions/:splat"
	status = 200

[[headers]]
	for = "/ap/user/blog"
	[headers.values]
		Content-Type = "application/activity+json"

[[headers]]
	for = "/.well-known/webfinger"
	[headers.values]
		Content-Type = "application/activity+json"