[build]
	publish = "/public"
	edge-functions = "/netlify/edge-functions"

[build.environment]
	GO_VERSION = "1.23"

[functions]
	directory = "netlify/functions"

[[edge_functions]]
	path = "/ap/inbox"
	function = "inbox"

[[edge_functions]]
	path = "/posts/*"
	function = "post2activity"

[[redirects]]
	from="/ap/outbox"
	to="/ap/outbox.json"
	status = 200

[[redirects]]
	from="/ap/*"
	to="/.netlify/functions/:splat"
	status = 200

[[redirects]]
	from="/posts/:title/replies"
	to="/.netlify/functions/reply-service?id=:title"
	status = 301

[[redirects]]
	from="/posts/:title/likes"
	to="/.netlify/functions/likes-and-shares?id=:title"
	status = 301
	[redirects.headers]
		X-From = "Netlify"
		X-Col-Name = "shares"
		Content-Type = "text/xml; charset=utf-8"

[[redirects]]
	from="/posts/:title/shares"
	to="/.netlify/functions/likes-and-shares?id=:title"
	status = 301
	[redirects.headers]
		X-Col-Name = "shares"

[[headers]]
	for = "/ap/user/blog"
	[headers.values]
		Content-Type = "application/activity+json"

[[headers]]
	for = "/.well-known/webfinger"
	[headers.values]
		Content-Type = "application/activity+json"

[[headers]]
	for = "/posts/*"
	[headers.values]
		Content-Type = "text/html; charset=utf-8"